apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: rudis-reifenklicker
  labels:
    app: postgres
spec:
  # Regulaerer ClusterIP-Service, auf den sich das Backend verbindet.
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
